system:
    site:
        image_variations:
                    small:
                        reference: ~
                        filters:
                            - {name: geometry/scaledownonly, params: [400, 350]}
    frontend_group:
        location_view:
            full:
                article:
                    template: "TuteiBaseBundle:content/article:full.html.twig"
                    match:
                        Identifier\ContentType: [article]
                
                folder:
                    template: "TuteiBaseBundle:content/folder:full.html.twig"
                    match:
                        Identifier\ContentType: [folder]
                        
                gallery:
                    template: "TuteiBaseBundle:content/gallery:full.html.twig"
                    match:
                        Identifier\ContentType: [gallery]
                        
                default:
                    template: "TuteiBaseBundle:content/default:full.html.twig"
                    match:
                        UrlAlias: "/"
            line:
                article:
                    template: "TuteiBaseBundle:content/article:line.html.twig"
                    match:
                        Identifier\ContentType: [article]
                        
                folder:
                    template: "TuteiBaseBundle:content/folder:line.html.twig"
                    match:
                        Identifier\ContentType: [folder]
                        
                image:
                    template: "TuteiBaseBundle:content/image:line.html.twig"
                    match:
                        Identifier\ContentType: [image]
                        
                default:
                    template: "TuteiBaseBundle:content/default:line.html.twig"
                    match:
                        UrlAlias: "/"
                        
            menu_item:
                default:
                    template: "TuteiBaseBundle:content/default:menu_item.html.twig"
                    match:
                        UrlAlias: "/"
                        
            box:
                default:
                    template: "TuteiBaseBundle:content/default:box.html.twig"
                    match:
                        UrlAlias: "/"
                        
            search:
                default:
                    template: "TuteiBaseBundle:content/default:search.html.twig"
                    match:
                        UrlAlias: "/"
                        
            block:

                default:
                    template: "TuteiBaseBundle:content/default:block.html.twig"
                    match:
                        UrlAlias: "/"