parameters:    
    
    project.menufilter.top:
                - folder
                - gallery
                # - article/menu
    project.menufilter.side:
                - folder
                - gallery
                # - article/menu
                
    project.list.block: [block_item]
    project.list.infobox: [article, link]
    project.list.folder: [article, link, folder]
                
    project.structure.folder: [article, folder]
    
    
    project.line_list.limit: 5