parameters:    
    
    project.menufilter.top:
                - folder
                # - article/menu
    project.menufilter.side:
                - folder
                # - article/menu
                
    project.list.block: [block_item]
    project.list.infobox: [article, link]
    project.list.folder: [article, link, folder]
                
    project.structure.folder: [article, folder]